dorknozzle/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using dorknozzle.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;



namespace dorknozzle.Controllers
{
    [Authorize]
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
        DorknozzleDbContext db = new DorknozzleDbContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        #region Autoryzacja

        public ActionResult ListaRol()
        {
            var roles = db.Roles.ToList();
            return View(roles);
        }

        public ActionResult UtworzRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UtworzRole(FormCollection collection)
        {
            try
            {
                db.Roles.Add(
                    new IdentityRole()//Microsoft.AspNet.Identity.EntityFramework.
                    {
                        Name = collection["RoleName"]
                    });
                db.SaveChanges();
                ViewBag.ResultMessage = "Rola utworzona pomyślnie";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult EdytujRole(string RoleName)
        {

            var role = db.Roles.FirstOrDefault(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase));

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EdytujRole(IdentityRole role)
        {
            try
            {
                var isRole = db.Roles.FirstOrDefault(r => r.Name.Equals(role.Name, StringComparison.CurrentCultureIgnoreCase));
                if (isRole == null)
                {
                    db.Entry(role).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("ListaRol");
                }
                else
                {
                    ViewBag.Blad = "Rola o takiej nazwie już istnieje";
                    return View(role);
                }
            }
            catch
            {
                return View();

            }
        }

        public ActionResult DodajRoleDoUzytkownika()
        {
            var list = db.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            var userList = db.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();

            ViewBag.Roles = list;
            ViewBag.Users = userList;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DodajRoleDoUzytkownika(string UserName, string RoleName)
        {
            Uzytkownik user = (Uzytkownik)db.Users.FirstOrDefault(u => u.UserName.Equals(UserName, StringComparison.InvariantCultureIgnoreCase));
            var um = new UserManager<Uzytkownik>(new UserStore<Uzytkownik>(new DorknozzleDbContext()));

            um.AddToRole(user.Id, RoleName);

            var list = db.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();

            ViewBag.Roles = list;
            ViewBag.Powterdzenie = "Rola została dodana";

            return RedirectToAction("ListaRol");
        }

        public ActionResult WyswietlRoleUzytkownika()
        {
            var userList = db.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WyswietlRoleUzytkownika(string UserName)
        {
            var list = db.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
                           new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }
                           ).ToList();
            ViewBag.Roles = list;

            var userList = db.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userList;

            if (!string.IsNullOrWhiteSpace(UserName))
            {
                Uzytkownik user = (Uzytkownik)db.Users.FirstOrDefault(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase));
                var um = new UserManager<Uzytkownik>(new UserStore<Uzytkownik>
                (new DorknozzleDbContext()));

                ViewBag.RolesForThisUser = um.GetRoles(user.Id);
            }
            return View("WyswietlRoleUzytkownika");
        }

        public ActionResult UsunRoleUzytkownikowi()
        {
            var list = db.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            var userList = db.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();

            ViewBag.Roles = list;
            ViewBag.Users = userList;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UsunRoleUzytkownikowi(string UserName, string RoleName)
        {

            var um = new UserManager<Uzytkownik>(new UserStore<Uzytkownik>(new DorknozzleDbContext()));

            Uzytkownik user = (Uzytkownik)db.Users.FirstOrDefault(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase));

            if (um.IsInRole(user.Id, RoleName))
            {
                um.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultSuccess = "Rola została usunięta!";
            }
            else
            {
                ViewBag.ResultWarning = "Ten użytkownik nie posiada takiej roli.";
            }

            // prepopulat roles for the view dropdown

            var list = db.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();

            ViewBag.Roles = list;

            return RedirectToAction("ListaRol");

        }
        #endregion //Autoryzacja
    }
}

dorknozzle/Controllers/DzialyController.cs
using System.Linq;
using System.Web.Mvc;
using dorknozzle.Models;
using dorknozzle.Repositories;

namespace dorknozzle.Controllers
{
    public class DzialyController : Controller
    {
        private readonly PracownicyRepository _pracownicyRepository;
        private readonly DzialRepository _dzialyRepository;
        public DzialyController()
        {
            _pracownicyRepository = new PracownicyRepository();
            _dzialyRepository = new DzialRepository();
        }

        public ActionResult Index()
        {
            return View(_dzialyRepository.GetAllDepartment());
        }

        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
                return PartialView("_create");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DzialId,Nazwa")] Dzialy dzialy)
        {
            if (ModelState.IsValid)
            {
                _dzialyRepository.Add(dzialy);
                _dzialyRepository.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dzialy);
        }

        public ActionResult Edit(int id = 0)
        {
            Dzialy dzialy = _dzialyRepository.GetDepartmentById(id);
            if (dzialy == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
                return PartialView("_edit", dzialy);

            return View(dzialy);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DzialId,Nazwa")] Dzialy dzialy)
        {
            if (ModelState.IsValid)
            {
                _dzialyRepository.Edit(dzialy);
                _dzialyRepository.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dzialy);
        }

        public ActionResult Delete(int id = 0)
        {
            Dzialy dzialy = _dzialyRepository.GetDepartmentById(id);
            if (dzialy == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
                return PartialView("_delete", dzialy);

            return View(dzialy);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dzialy dzialy = _dzialyRepository.GetDepartmentById(id);
            _dzialyRepository.Delete(dzialy);
            _dzialyRepository.SaveChanges();    
            return RedirectToAction("Index");
        }

        public ActionResult ListaPracownikow(int id = 0)
        {
            IQueryable<Pracownicy> lista = _pracownicyRepository.GetAllEmployessByDepartmentId(id);
            
            if(Request.IsAjaxRequest())
                return PartialView("_listaPracownikow", lista);

            return View(lista);
        }

    }
}

dorknozzle/Controllers/KsiazkaController.cs
using System.Linq;
using System.Web.Mvc;
using dorknozzle.Models.ViewModel;
using dorknozzle.Repositories;

namespace dorknozzle.Controllers
{
    public class KsiazkaController : Controller
    {
        private readonly KsiazkaAdresowaRepository ksiazkaAdresowRepository;
        private readonly PracownicyRepository pracownicyRepository;
        public KsiazkaController()
        {
            ksiazkaAdresowRepository = new KsiazkaAdresowaRepository();
            pracownicyRepository = new PracownicyRepository();
        }

        public ActionResult Index()
        {
            IQueryable<KsiazkaAdresowaViewModel> listaAdresow = ksiazkaAdresowRepository.GetAllBookAddress();
            return View(listaAdresow);
        }


        public ActionResult Details(int id)
        {
            var pracownik = pracownicyRepository.GetAllDetailsEmplyessById(id);
            return PartialView("_details2", pracownik);
        }

    }
}

dorknozzle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nazwa aplikacji", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — moja aplikacja platformy ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

dorknozzle/Views/Shared/_LayoutDorknozzle.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dorknozzle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", false)
</head>
<body>

    <div class="container">
        <header id="header">
            <div class="row">
                <div class="col-md-8 headerImage">

                </div>
                <div class="col-md-4">
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </header>

        <div class="row">

            <div class="col-md-2">
                <nav>
                    <ul class="navImage">
                        <li><a href="@Url.Content("/")">Strona główna</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a href="@Url.Action("Create", "Pracownicy")">Uzupełnij profil</a></li>
                        }
                        <li><a href="@Url.Action("Create", "PomocTechniczna")">Pomoc techniczna</a></li>
                        <li><a href="@Url.Action("Index", "Pracownicy")">Pracownicy</a></li>
                        <li><a href="@Url.Action("Index", "Ksiazka")">Książka adresowa</a></li>
                        <li><a href="@Url.Action("Index", "Dzialy")">Działy</a></li>
                        @if (User.IsInRole("admin"))
                        {
                            <li><a href="@Url.Action("Index", "Admin")">Narzędzia administracyjne</a></li>
                        }

                    </ul>
                </nav>
            </div>

            <div class="col-md-10">
                @if (@TempData["Message"] != null)
                {
                    <div class="alert alert-success">
                        @TempData["Message"]
                    </div>
                }

                @if (@TempData["Error"] != null)
                {
                    <div class="alert alert-success">
                        @TempData["Error"]
                    </div>
                }

                @RenderBody()
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <footer class="text-center">
                    <p>&copy; @DateTime.Now.Year - Dorknozzle</p>
                </footer>
            </div>
        </div>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>