dorknozzle/Models/PomocTechniczna.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace dorknozzle.Models
{
    public enum Status
    {
        Oczekuje,
        Realizacja,
        Zrealizowane
    }

    public class PomocTechniczna
    {
        [Key]
        public int PomocTechnicznaId { get; set; }

        [Display(Name = "Użytkownik")]
        public string UserId { get; set; }

        [Required(ErrorMessage = "Numer stanowiska jest wymagany.")]
        [Display(Name = "Numer stanowiska")]
        public string NunerStanowiska { get; set; }

        public string AdresIp { get; set; }

        [Display(Name = "Data zgłoszenia")]
        [DisplayFormat(DataFormatString = "{0:yy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        public DateTime DataZgloszenia { get; set; }

        [Required(ErrorMessage = "Opis jest wymagany.")]
        public string Opis { get; set; }

        public Status Status { get; set; }

        [Required(ErrorMessage = "Kategoria jest wymagana.")]
        [Display(Name = "Kategoria")]
        public int KategoriaId { get; set; }
        
        public virtual PomocTechnicznaKategorie PomocTechnicznaKategorie { get; set; }

        [Required(ErrorMessage = "Temat jest wymagany.")]
        [Display(Name = "Temat")]
        public int TematId { get; set; }
        
        public virtual PomocTechnicznaTematy PomocTechnicznaTematy { get; set; }
    }
}

dorknozzle/Controllers/PomocTechnicznaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dorknozzle.Models;
using Microsoft.AspNet.Identity;

namespace dorknozzle.Admin
{        
    [Authorize]
    public class PomocTechnicznaController : Controller
    {
        private DorknozzleDbContext db = new DorknozzleDbContext();

        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var pomocTechniczna = db.PomocTechniczna.Include(p => p.PomocTechnicznaKategorie).Include(p => p.PomocTechnicznaTematy);
            return View(pomocTechniczna.ToList());
        }

        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PomocTechniczna pomocTechniczna = db.PomocTechniczna.Find(id);
            if (pomocTechniczna == null)
            {
                return HttpNotFound();
            }
            return View(pomocTechniczna);
        }

        public ActionResult Create()
        {
            ViewBag.KategoriaId = new SelectList(db.PomocTechnicznaKategorie, "KategoriaId", "Nazwa");
            ViewBag.TematId = new SelectList(db.PomocTechnicznaTematy, "TematId", "Nazwa");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PomocTechnicznaId,NunerStanowiska,Opis,KategoriaId,TematId")] PomocTechniczna pomocTechniczna)
        {
            pomocTechniczna.Status = Status.Oczekuje;
            pomocTechniczna.DataZgloszenia = DateTime.Now;
            pomocTechniczna.UserId = User.Identity.GetUserId();
            pomocTechniczna.AdresIp = Request.UserHostAddress;

            if (pomocTechniczna.TematId == 0)
                ModelState.AddModelError("TematId", "Wybierz poprawnie temat");

            if (ModelState.IsValid)
            {
                db.PomocTechniczna.Add(pomocTechniczna);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriaId = new SelectList(db.PomocTechnicznaKategorie, "KategoriaId", "Nazwa", pomocTechniczna.KategoriaId);
            ViewBag.TematId = new SelectList(db.PomocTechnicznaTematy, "TematId", "Nazwa", pomocTechniczna.TematId);
            return View(pomocTechniczna);
        }
        
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PomocTechniczna pomocTechniczna = db.PomocTechniczna.Find(id);
            if (pomocTechniczna == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriaId = new SelectList(db.PomocTechnicznaKategorie, "KategoriaId", "Nazwa", pomocTechniczna.KategoriaId);
            ViewBag.TematId = new SelectList(db.PomocTechnicznaTematy, "TematId", "Nazwa", pomocTechniczna.TematId);
            return View(pomocTechniczna);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "PomocTechnicznaId,UserId,NunerStanowiska,AdresIp,DataZgloszenia,Opis,Status,KategoriaId,TematId")] PomocTechniczna pomocTechniczna)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pomocTechniczna).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriaId = new SelectList(db.PomocTechnicznaKategorie, "KategoriaId", "Nazwa", pomocTechniczna.KategoriaId);
            ViewBag.TematId = new SelectList(db.PomocTechnicznaTematy, "TematId", "Nazwa", pomocTechniczna.TematId);
            return View(pomocTechniczna);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PomocTechniczna pomocTechniczna = db.PomocTechniczna.Find(id);
            if (pomocTechniczna == null)
            {
                return HttpNotFound();
            }
            return View(pomocTechniczna);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            PomocTechniczna pomocTechniczna = db.PomocTechniczna.Find(id);
            db.PomocTechniczna.Remove(pomocTechniczna);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ListaTematow(int id = 0)
        {
            var listaTematow =
                db.PomocTechnicznaTematy.Where(t => t.KategoriaId == id).Select(x => new { idTematu = x.TematId, nazwaTematu = x.Nazwa }).ToList();
            return Json(listaTematow, JsonRequestBehavior.AllowGet);

        }
    }
}

dorknozzle/Views/PomocTechniczna/Create.cshtml
@model dorknozzle.Models.PomocTechniczna

@{
    ViewBag.Title = "Dodaj zgłoszenie";
    Layout = "~/Views/Shared/_LayoutDorknozzle.cshtml";
}

<h3>Dodaj zgłoszenie</h3>

@using (Html.BeginForm("Create", "PomocTechniczna", FormMethod.Post, htmlAttributes: new { @id = "formularz" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.KategoriaId, "Kategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriaId", null, "Wybierz kategorię", htmlAttributes: new { @class = "form-control", @id = "kategorie" })
                @Html.ValidationMessageFor(model => model.KategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TematId, "Temat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TematId", null, "Wybierz temat", htmlAttributes: new { @class = "form-control", @id = "tematy" })
                @Html.ValidationMessageFor(model => model.TematId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NunerStanowiska, htmlAttributes: new { @class = "control-label col-md-2", @type = "number" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NunerStanowiska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NunerStanowiska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Opis, 5, 40,  new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

@section scripts{
    <script type="text/javascript">
        $('document').ready(function () {

            //jeśli istnieje już select-tematy o id: tematy, to usuń elementy z listy
            //if ($('#tematy').length > 0)
            //    $('#tematy option').remove();

            //przypisanie akcji wywołania dodatkowej listy do zdarzenia typu change
            $('#kategorie').on('change', function() {

                var id = $(this).val();

                //jeśli istnieje już select-tematy o id: tematy, to usuń elementy z listy
                if ($('#tematy').length > 0)
                    $('#tematy option').remove();

                $.ajax({
                    method: "GET",
                    url: "/PomocTechniczna/ListaTematow/",
                    data: { id: id },
                    success: function (data) {

                        var lista = $('#tematy');
        
                                $.each(data, function (key, val) {
                                    var option = $('<option/>');
                                    option.attr('value', val.idTematu)
                                        .html(val.nazwaTematu)
                                        .appendTo(lista);
                                });
                    },
                    error: function() {
                        alert("Wystąpił bład spróbuj później");
                    }
                });
            });
         });
    </script>

}

dorknozzle/Views/PomocTechniczna/Delete.cshtml
@model dorknozzle.Models.PomocTechniczna

@{
    ViewBag.Title = "Usuń zgłoszenie";
    Layout = "~/Views/Shared/_LayoutDorknozzle.cshtml";
}

<h3>Czy jesteś pewien, że chcesz usunąć zgłoszenie?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PomocTechnicznaKategorie.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PomocTechnicznaKategorie.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PomocTechnicznaTematy.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PomocTechnicznaTematy.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NunerStanowiska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NunerStanowiska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdresIp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdresIp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataZgloszenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataZgloszenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

dorknozzle/Views/PomocTechniczna/Details.cshtml
@model dorknozzle.Models.PomocTechniczna

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDorknozzle.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PomocTechniczna</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PomocTechnicznaKategorie.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PomocTechnicznaKategorie.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PomocTechnicznaTematy.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PomocTechnicznaTematy.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NunerStanowiska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NunerStanowiska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdresIp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdresIp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataZgloszenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataZgloszenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PomocTechnicznaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dorknozzle/Views/PomocTechniczna/Edit.cshtml
@model dorknozzle.Models.PomocTechniczna

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDorknozzle.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PomocTechniczna</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PomocTechnicznaId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NunerStanowiska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NunerStanowiska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NunerStanowiska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdresIp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdresIp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdresIp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataZgloszenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataZgloszenia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataZgloszenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriaId, "KategoriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TematId, "TematId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TematId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TematId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

dorknozzle/Views/PomocTechniczna/Index.cshtml
@model IEnumerable<dorknozzle.Models.PomocTechniczna>

@{
    ViewBag.Title = "Lista zgłoszeń";
    Layout = "~/Views/Shared/_LayoutDorknozzle.cshtml";
}

<h3>Lista zgłoszeń</h3>

<p>
    @Html.ActionLink("Dodaj zgłoszenie", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Podkategoria")
        </th>
        <th>
            @Html.DisplayName("Kategoria")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NunerStanowiska)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdresIp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataZgloszenia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.PomocTechnicznaTematy.Nazwa, "Edit", new { id = item.PomocTechnicznaId }) 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PomocTechnicznaKategorie.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NunerStanowiska)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdresIp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataZgloszenia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id = item.PomocTechnicznaId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.PomocTechnicznaId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.PomocTechnicznaId })
        </td>
    </tr>
}

</table>